def generate_python_code(idea: str, project_type: str, complexity: str) -> str:
    templates = {
        "Mobile App": _mobile_template,
        "Website": _website_template,
        "Full Stack": _fullstack_template,
    }
    generator = templates.get(project_type, _website_template)
    code = generator(idea, complexity)
    code += _readme_section(idea, project_type, complexity)
    return code


def _readme_section(idea: str, project_type: str, complexity: str) -> str:
    folder = idea.strip().replace(' ', '_').lower()[:30]

    install_map = {
        'Website': {
            'Simple':       'pip install flask',
            'Intermediate': 'pip install flask',
            'Advanced':     'pip install flask flask-sqlalchemy flask-jwt-extended werkzeug',
        },
        'Mobile App': {
            'Simple':       'pip install fastapi uvicorn',
            'Intermediate': 'pip install fastapi uvicorn',
            'Advanced':     'pip install fastapi uvicorn sqlalchemy passlib[bcrypt] python-jose',
        },
        'Full Stack': {
            'Simple':       'pip install django',
            'Intermediate': 'pip install django djangorestframework',
            'Advanced':     'pip install django djangorestframework celery redis django-filter',
        },
    }

    run_map = {
        'Website': {
            'Simple':       'python app.py',
            'Intermediate': 'python app.py',
            'Advanced':     'python app.py',
        },
        'Mobile App': {
            'Simple':       'uvicorn main:app --reload',
            'Intermediate': 'uvicorn main:app --reload --port 8000',
            'Advanced':     'uvicorn main:app --reload --port 8000',
        },
        'Full Stack': {
            'Simple':       'python manage.py runserver',
            'Intermediate': 'python manage.py runserver',
            'Advanced':     'python manage.py runserver\n# Also start Celery: celery -A your_project worker --loglevel=info',
        },
    }

    structure_map = {
        'Website': {
            'Simple': f'''{folder}/
├── app.py          # Main Flask application
├── requirements.txt
└── README.md''',
            'Intermediate': f'''{folder}/
├── app.py          # Flask app + REST API + frontend
├── requirements.txt
└── README.md''',
            'Advanced': f'''{folder}/
├── app.py          # Flask + SQLAlchemy + JWT
├── {folder}.db     # SQLite database (auto-created)
├── requirements.txt
└── README.md''',
        },
        'Mobile App': {
            'Simple': f'''{folder}/
├── main.py         # FastAPI app
├── requirements.txt
└── README.md''',
            'Intermediate': f'''{folder}/
├── main.py         # FastAPI + profiles + feed
├── requirements.txt
└── README.md''',
            'Advanced': f'''{folder}/
├── main.py         # FastAPI + SQLAlchemy + OAuth2
├── {folder}.db     # SQLite database (auto-created)
├── requirements.txt
└── README.md''',
        },
        'Full Stack': {
            'Simple': f'''{folder}/
├── manage.py
├── {folder}/
│   ├── models.py   # Project model
│   ├── views.py    # API views
│   └── urls.py
├── requirements.txt
└── README.md''',
            'Intermediate': f'''{folder}/
├── manage.py
├── {folder}/
│   ├── models.py   # Category + Item models
│   ├── serializers.py
│   ├── views.py    # DRF ViewSets
│   └── urls.py
├── requirements.txt
└── README.md''',
            'Advanced': f'''{folder}/
├── manage.py
├── {folder}/
│   ├── models.py   # User, Project, Comment, Tag
│   ├── serializers.py
│   ├── views.py    # DRF ViewSets + filters
│   ├── tasks.py    # Celery async tasks
│   └── urls.py
├── celery.py       # Celery config
├── requirements.txt
└── README.md''',
        },
    }

    install_cmd = install_map.get(project_type, {}).get(complexity, 'pip install -r requirements.txt')
    run_cmd = run_map.get(project_type, {}).get(complexity, 'python app.py')
    structure = structure_map.get(project_type, {}).get(complexity, f'{folder}/')

    return f'''

# =============================================================================
# README
# =============================================================================
#
# Project : {idea}
# Type    : {project_type}
# Complexity: {complexity}
# Generated by: ProtoPy - Python Prototype Generator
#
# ----------------------------------------------------------------------------
# FOLDER STRUCTURE
# ----------------------------------------------------------------------------
#
# {chr(10).join('# ' + line for line in structure.splitlines())}
#
# ----------------------------------------------------------------------------
# SETUP & RUN
# ----------------------------------------------------------------------------
#
# Step 1 — Create a virtual environment
#   python -m venv venv
#
# Step 2 — Activate it
#   Windows : venv\\Scripts\\activate
#   Mac/Linux: source venv/bin/activate
#
# Step 3 — Install dependencies
#   {install_cmd}
#
# Step 4 — Run the app
#   {run_cmd}
#
# ----------------------------------------------------------------------------
# REQUIREMENTS FILE  (save as requirements.txt)
# ----------------------------------------------------------------------------
#
# {chr(10).join('# ' + pkg for pkg in install_cmd.replace('pip install ', '').split())}
#
# ----------------------------------------------------------------------------
# NOTES
# ----------------------------------------------------------------------------
#
# - Copy this file into your project folder as app.py / main.py / models.py
# - SQLite database is created automatically on first run
# - Change SECRET_KEY before deploying to production
# - This prototype was generated by ProtoPy (http://localhost:5173)
#
# =============================================================================
'''


def _header(idea, project_type, complexity):
    return f'''"""
ProtoPy Generated Code
Project: {idea}
Type: {project_type}
Complexity: {complexity}
Generated by: ProtoPy - Python Prototype Generator
"""
'''


def _website_template(idea, complexity):
    code = _header(idea, "Website", complexity)

    if complexity == "Simple":
        code += '''from flask import Flask, render_template_string

app = Flask(__name__)

HTML = """
<!DOCTYPE html>
<html>
<head><title>''' + idea + '''</title></head>
<body>
  <h1>Welcome to ''' + idea + '''</h1>
  <p>Your website is ready to go!</p>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML)

@app.route("/about")
def about():
    return "<h1>About Us</h1><p>This is the about page.</p>"

if __name__ == "__main__":
    app.run(debug=True)
'''

    elif complexity == "Intermediate":
        code += '''from flask import Flask, render_template_string, request, jsonify
from datetime import datetime

app = Flask(__name__)
items = []

@app.route("/")
def home():
    return render_template_string("""
    <!DOCTYPE html>
    <html>
    <head>
      <title>''' + idea + '''</title>
      <style>
        body { font-family: Arial; max-width: 800px; margin: 50px auto; padding: 20px; }
        .card { border: 1px solid #ddd; padding: 15px; margin: 10px 0; border-radius: 8px; }
        button { background: #4f46e5; color: white; padding: 8px 16px; border: none; border-radius: 4px; cursor: pointer; }
      </style>
    </head>
    <body>
      <h1>''' + idea + '''</h1>
      <div id="app">
        <input id="input" type="text" placeholder="Enter item..." />
        <button onclick="addItem()">Add</button>
        <div id="list"></div>
      </div>
      <script>
        async function addItem() {
          const val = document.getElementById("input").value;
          await fetch("/api/items", { method: "POST", headers: {"Content-Type":"application/json"}, body: JSON.stringify({name: val}) });
          loadItems();
        }
        async function loadItems() {
          const res = await fetch("/api/items");
          const data = await res.json();
          document.getElementById("list").innerHTML = data.map(i => `<div class="card">${i.name}</div>`).join("");
        }
        loadItems();
      </script>
    </body>
    </html>
    """)

@app.route("/api/items", methods=["GET"])
def get_items():
    return jsonify(items)

@app.route("/api/items", methods=["POST"])
def add_item():
    data = request.get_json()
    item = {"id": len(items) + 1, "name": data.get("name"), "created_at": str(datetime.now())}
    items.append(item)
    return jsonify(item), 201

if __name__ == "__main__":
    app.run(debug=True)
'''

    else:  # Advanced
        code += '''from flask import Flask, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from flask_jwt_extended import JWTManager, create_access_token, jwt_required, get_jwt_identity
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///''' + idea.replace(" ", "_").lower() + '''.db"
app.config["JWT_SECRET_KEY"] = "your-secret-key-change-in-production"

db = SQLAlchemy(app)
jwt = JWTManager(app)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


@app.route("/api/register", methods=["POST"])
def register():
    data = request.get_json()
    if User.query.filter_by(email=data["email"]).first():
        return jsonify({"error": "Email already exists"}), 400
    user = User(email=data["email"])
    user.set_password(data["password"])
    db.session.add(user)
    db.session.commit()
    return jsonify({"message": "User created successfully"}), 201


@app.route("/api/login", methods=["POST"])
def login():
    data = request.get_json()
    user = User.query.filter_by(email=data["email"]).first()
    if not user or not user.check_password(data["password"]):
        return jsonify({"error": "Invalid credentials"}), 401
    token = create_access_token(identity=user.id)
    return jsonify({"access_token": token})


@app.route("/api/posts", methods=["GET"])
@jwt_required()
def get_posts():
    posts = Post.query.filter_by(user_id=get_jwt_identity()).all()
    return jsonify([{"id": p.id, "title": p.title, "content": p.content} for p in posts])


@app.route("/api/posts", methods=["POST"])
@jwt_required()
def create_post():
    data = request.get_json()
    post = Post(title=data["title"], content=data.get("content", ""), user_id=get_jwt_identity())
    db.session.add(post)
    db.session.commit()
    return jsonify({"id": post.id, "title": post.title}), 201


if __name__ == "__main__":
    with app.app_context():
        db.create_all()
    app.run(debug=True)
'''

    return code


def _mobile_template(idea, complexity):
    code = _header(idea, "Mobile App", complexity)

    if complexity == "Simple":
        code += '''# Mobile App Backend using FastAPI
# Frontend: Use React Native or Flutter with this API

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="''' + idea + '''")

class Item(BaseModel):
    name: str
    description: str = ""

items = []

@app.get("/")
def root():
    return {"app": "''' + idea + '''", "status": "running"}

@app.get("/items")
def list_items():
    return items

@app.post("/items")
def create_item(item: Item):
    new_item = {"id": len(items) + 1, **item.dict()}
    items.append(new_item)
    return new_item

# Run: uvicorn main:app --reload
'''

    elif complexity == "Intermediate":
        code += '''from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

app = FastAPI(title="''' + idea + '''", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class UserProfile(BaseModel):
    username: str
    bio: Optional[str] = ""
    avatar_url: Optional[str] = ""

class Post(BaseModel):
    title: str
    body: str
    tags: List[str] = []

users_db = {}
posts_db = []

@app.get("/api/profile/{username}")
def get_profile(username: str):
    if username not in users_db:
        raise HTTPException(status_code=404, detail="User not found")
    return users_db[username]

@app.post("/api/profile")
def create_profile(profile: UserProfile):
    users_db[profile.username] = {**profile.dict(), "created_at": str(datetime.now())}
    return users_db[profile.username]

@app.get("/api/feed")
def get_feed(skip: int = 0, limit: int = 10):
    return posts_db[skip: skip + limit]

@app.post("/api/posts")
def create_post(post: Post):
    new_post = {"id": len(posts_db) + 1, **post.dict(), "created_at": str(datetime.now())}
    posts_db.append(new_post)
    return new_post

@app.delete("/api/posts/{post_id}")
def delete_post(post_id: int):
    global posts_db
    posts_db = [p for p in posts_db if p["id"] != post_id]
    return {"message": "Deleted"}

# Run: uvicorn main:app --reload --port 8000
'''

    else:  # Advanced
        code += '''from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session, relationship
from pydantic import BaseModel, EmailStr
from passlib.context import CryptContext
from jose import JWTError, jwt
from datetime import datetime, timedelta
from typing import List, Optional

DATABASE_URL = "sqlite:///./''' + idea.replace(" ", "_").lower() + '''.db"
SECRET_KEY = "your-secret-key"
ALGORITHM = "HS256"

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/token")

app = FastAPI(title="''' + idea + '''")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])


class UserModel(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    posts = relationship("PostModel", back_populates="author")


class PostModel(Base):
    __tablename__ = "posts"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)
    content = Column(Text)
    author_id = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, default=datetime.utcnow)
    author = relationship("UserModel", back_populates="posts")


Base.metadata.create_all(bind=engine)


class UserCreate(BaseModel):
    email: str
    password: str

class PostCreate(BaseModel):
    title: str
    content: str

class Token(BaseModel):
    access_token: str
    token_type: str


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_token(data: dict):
    expire = datetime.utcnow() + timedelta(hours=24)
    return jwt.encode({**data, "exp": expire}, SECRET_KEY, algorithm=ALGORITHM)


def get_current_user(token: str = Depends(oauth2_scheme), db: Session = Depends(get_db)):
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        user = db.query(UserModel).filter(UserModel.id == payload.get("sub")).first()
        if not user:
            raise HTTPException(status_code=401, detail="Invalid token")
        return user
    except JWTError:
        raise HTTPException(status_code=401, detail="Invalid token")


@app.post("/api/register", response_model=Token)
def register(user: UserCreate, db: Session = Depends(get_db)):
    if db.query(UserModel).filter(UserModel.email == user.email).first():
        raise HTTPException(status_code=400, detail="Email already registered")
    db_user = UserModel(email=user.email, hashed_password=pwd_context.hash(user.password))
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return {"access_token": create_token({"sub": db_user.id}), "token_type": "bearer"}


@app.post("/api/token", response_model=Token)
def login(form: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    user = db.query(UserModel).filter(UserModel.email == form.username).first()
    if not user or not pwd_context.verify(form.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    return {"access_token": create_token({"sub": user.id}), "token_type": "bearer"}


@app.get("/api/posts")
def get_posts(db: Session = Depends(get_db), current_user: UserModel = Depends(get_current_user)):
    return db.query(PostModel).filter(PostModel.author_id == current_user.id).all()


@app.post("/api/posts")
def create_post(post: PostCreate, db: Session = Depends(get_db), current_user: UserModel = Depends(get_current_user)):
    db_post = PostModel(**post.dict(), author_id=current_user.id)
    db.add(db_post)
    db.commit()
    db.refresh(db_post)
    return db_post
'''

    return code


def _fullstack_template(idea, complexity):
    code = _header(idea, "Full Stack", complexity)

    if complexity == "Simple":
        code += '''# Full Stack App - Django Backend
# Run: python manage.py runserver

from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


# views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import json


@csrf_exempt
def projects(request):
    if request.method == "GET":
        data = list(Project.objects.values("id", "name", "description", "created_at"))
        return JsonResponse(data, safe=False)
    elif request.method == "POST":
        body = json.loads(request.body)
        project = Project.objects.create(name=body["name"], description=body.get("description", ""))
        return JsonResponse({"id": project.id, "name": project.name}, status=201)


# urls.py
from django.urls import path
urlpatterns = [
    path("api/projects/", projects),
]
'''

    elif complexity == "Intermediate":
        code += '''# Full Stack App - Django REST Framework
# Install: pip install djangorestframework

from django.db import models
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import action
from rest_framework.response import Response


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Item(models.Model):
    STATUS_CHOICES = [("draft", "Draft"), ("published", "Published"), ("archived", "Archived")]
    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = "__all__"


class ItemSerializer(serializers.ModelSerializer):
    category_name = serializers.CharField(source="category.name", read_only=True)
    owner_email = serializers.CharField(source="owner.email", read_only=True)

    class Meta:
        model = Item
        fields = "__all__"
        read_only_fields = ("owner", "created_at", "updated_at")


class ItemViewSet(viewsets.ModelViewSet):
    serializer_class = ItemSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Item.objects.filter(owner=self.request.user)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

    @action(detail=False, methods=["get"])
    def published(self, request):
        items = self.get_queryset().filter(status="published")
        return Response(ItemSerializer(items, many=True).data)


class CategoryViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


# urls.py
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register("items", ItemViewSet, basename="item")
router.register("categories", CategoryViewSet)
urlpatterns = router.urls
'''

    else:  # Advanced
        code += '''# Full Stack App - Advanced Django + Celery + Redis + DRF
# Install: pip install django djangorestframework celery redis channels

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from rest_framework import serializers, viewsets, filters
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.decorators import action
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend
from celery import shared_task
import uuid


class User(AbstractUser):
    bio = models.TextField(blank=True)
    avatar = models.URLField(blank=True)
    is_verified = models.BooleanField(default=False)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Project(models.Model):
    VISIBILITY = [("public", "Public"), ("private", "Private"), ("team", "Team")]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owned_projects")
    collaborators = models.ManyToManyField(User, related_name="collaborated_projects", blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    visibility = models.CharField(max_length=10, choices=VISIBILITY, default="private")
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]


class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE, related_name="replies")
    created_at = models.DateTimeField(auto_now_add=True)


@shared_task
def send_notification_email(user_id, message):
    """Async task to send notification emails via Celery."""
    from django.core.mail import send_mail
    from django.contrib.auth import get_user_model
    User = get_user_model()
    user = User.objects.get(id=user_id)
    send_mail("Notification", message, "noreply@app.com", [user.email])


class ProjectSerializer(serializers.ModelSerializer):
    owner_email = serializers.CharField(source="owner.email", read_only=True)
    tags = serializers.SlugRelatedField(many=True, slug_field="name", queryset=Tag.objects.all())
    comment_count = serializers.SerializerMethodField()

    class Meta:
        model = Project
        fields = "__all__"
        read_only_fields = ("id", "owner", "created_at", "updated_at")

    def get_comment_count(self, obj):
        return obj.comments.count()


class ProjectViewSet(viewsets.ModelViewSet):
    serializer_class = ProjectSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ["visibility", "is_featured"]
    search_fields = ["title", "description"]
    ordering_fields = ["created_at", "updated_at"]

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(
            models.Q(owner=user) | models.Q(collaborators=user) | models.Q(visibility="public")
        ).distinct()

    def perform_create(self, serializer):
        project = serializer.save(owner=self.request.user)
        send_notification_email.delay(self.request.user.id, f"Project \'{project.title}\' created!")

    @action(detail=True, methods=["post"])
    def add_collaborator(self, request, pk=None):
        project = self.get_object()
        if project.owner != request.user:
            return Response({"error": "Only owner can add collaborators"}, status=403)
        email = request.data.get("email")
        try:
            user = User.objects.get(email=email)
            project.collaborators.add(user)
            return Response({"message": f"{email} added as collaborator"})
        except User.DoesNotExist:
            return Response({"error": "User not found"}, status=404)

    @action(detail=False, methods=["get"])
    def featured(self, request):
        projects = Project.objects.filter(is_featured=True, visibility="public")
        return Response(ProjectSerializer(projects, many=True).data)
'''

    return code
